/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.customerclient.view;

import com.mycompany.common.components.NoEditableTableModel;

/**
 *
 * @author CATELLO
 */
public class CurrentOrderView extends javax.swing.JFrame {

    /**
     * Creates new form CurrentOrderView
     */
    public CurrentOrderView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        providerLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        dishIngredientTextArea = new javax.swing.JTextArea();
        deliviryTimeLabel = new javax.swing.JLabel();
        tableLabel = new javax.swing.JLabel();
        providerField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        riderField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        orderStateField = new javax.swing.JTextField();
        riderNameLabel = new javax.swing.JLabel();
        deliveryTimeField = new javax.swing.JTextField();
        totalField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        dishTable = new javax.swing.JTable(){

            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    default:
                    return String.class;
                }
            }
        };
        refreshBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        dishDescriptionTextArea = new javax.swing.JTextArea();
        titleLabel = new javax.swing.JLabel();
        navBar = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        balanceBtn = new javax.swing.JButton();
        accountBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        providerLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        providerLabel.setText("Provider: ");

        dishIngredientTextArea.setColumns(20);
        dishIngredientTextArea.setRows(5);
        dishIngredientTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dish Ingredient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jScrollPane5.setViewportView(dishIngredientTextArea);

        deliviryTimeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deliviryTimeLabel.setText("Delivery time: ");

        tableLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableLabel.setText("Your order");

        providerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerFieldActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalLabel.setText("Total");

        riderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riderFieldActionPerformed(evt);
            }
        });

        stateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stateLabel.setText("Order State:  ");

        orderStateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderStateFieldActionPerformed(evt);
            }
        });

        riderNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        riderNameLabel.setText("Rider:");

        deliveryTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryTimeFieldActionPerformed(evt);
            }
        });

        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });

        dishTable.setModel(new NoEditableTableModel(
            new Object [][] {
                {null, null },
                {null, null },
                {null, null },
                {null, null }
            },
            new String [] {
                "<html><div style = 'text-align: center'>Dish Name</div></html>\"",
                "<html><div style = 'text-align: center'>Dish Price</div></html>\""
            },
            10)
    );
    jScrollPane3.setViewportView(dishTable);

    refreshBtn.setBackground(new java.awt.Color(44, 73, 129));
    refreshBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    refreshBtn.setText("Refresh");
    refreshBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            refreshBtnActionPerformed(evt);
        }
    });

    dishDescriptionTextArea.setColumns(20);
    dishDescriptionTextArea.setRows(5);
    dishDescriptionTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dish Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    jScrollPane4.setViewportView(dishDescriptionTextArea);

    titleLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
    titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titleLabel.setText("YOUR ORDER IN PROGRESS");

    navBar.setBackground(new java.awt.Color(146, 43, 32));

    logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
    logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    logoutBtn.setForeground(new java.awt.Color(5, 5, 5));
    logoutBtn.setText("Update Balance");
    logoutBtn.setBorderPainted(false);
    logoutBtn.setMaximumSize(new java.awt.Dimension(145, 29));
    logoutBtn.setMinimumSize(new java.awt.Dimension(145, 29));
    logoutBtn.setPreferredSize(new java.awt.Dimension(145, 29));
    logoutBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutBtnActionPerformed(evt);
        }
    });

    balanceBtn.setBackground(new java.awt.Color(255, 255, 255));
    balanceBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    balanceBtn.setText("Update Account");
    balanceBtn.setBorderPainted(false);
    balanceBtn.setPreferredSize(new java.awt.Dimension(145, 29));
    balanceBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            balanceBtnActionPerformed(evt);
        }
    });

    accountBtn.setBackground(new java.awt.Color(255, 255, 255));
    accountBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    accountBtn.setText("Log out");
    accountBtn.setBorderPainted(false);
    accountBtn.setPreferredSize(new java.awt.Dimension(145, 29));
    accountBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            accountBtnActionPerformed(evt);
        }
    });

    historyBtn.setBackground(new java.awt.Color(255, 255, 255));
    historyBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    historyBtn.setText("Order history");
    historyBtn.setBorderPainted(false);
    historyBtn.setPreferredSize(new java.awt.Dimension(145, 29));
    historyBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            historyBtnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
    navBar.setLayout(navBarLayout);
    navBarLayout.setHorizontalGroup(
        navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(navBarLayout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(108, 108, 108)
            .addComponent(balanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(101, 101, 101)
            .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(accountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18))
    );
    navBarLayout.setVerticalGroup(
        navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(navBarLayout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(balanceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(historyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(24, 24, 24))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane4)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(providerLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(providerField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(riderNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(riderField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(stateLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deliveryTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(deliviryTimeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(orderStateField))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(totalLabel)
                                    .addGap(7, 7, 7)
                                    .addComponent(totalField))
                                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addComponent(navBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
            .addComponent(titleLabel)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(deliviryTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(providerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(riderNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(providerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(riderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(orderStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(deliveryTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(tableLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalLabel)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 930, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 502, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void providerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerFieldActionPerformed

    private void riderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riderFieldActionPerformed

    private void orderStateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderStateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderStateFieldActionPerformed

    private void deliveryTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryTimeFieldActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void balanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceBtnActionPerformed

    private void accountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentOrderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountBtn;
    private javax.swing.JButton balanceBtn;
    private javax.swing.JTextField deliveryTimeField;
    private javax.swing.JLabel deliviryTimeLabel;
    private javax.swing.JTextArea dishDescriptionTextArea;
    private javax.swing.JTextArea dishIngredientTextArea;
    private javax.swing.JTable dishTable;
    private javax.swing.JButton historyBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel navBar;
    private javax.swing.JTextField orderStateField;
    private javax.swing.JTextField providerField;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField riderField;
    private javax.swing.JLabel riderNameLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
