/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.providerclient.view;

import com.mycompany.customerclient.view.*;
import com.formdev.flatlaf.FlatDarkLaf;
import com.mycompany.common.components.JButtonEditor;
import com.mycompany.common.components.JButtonRenderer;
import com.mycompany.common.components.JTextFieldPlaceholder;
import com.mycompany.common.components.NoEditableTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.JButton;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Amos
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {
            //   UIManager.
            UIManager.setLookAndFeel( new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        jTabbedPane1.setVisible(false);
        loginPanel.setVisible(false);
        this.signUpPanel.setVisible(false);
        this.newSingup.setVisible(false);
        this.providerView.setVisible(false);
        this.OrderViewerCustomer.setVisible(false);
        this.newLogin.setVisible(false);
        this.newViewMenu.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        signInBtn = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        passTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        signUpPanel = new javax.swing.JPanel();
        loginBtn1 = new javax.swing.JButton();
        signInBtn1 = new javax.swing.JButton();
        welcomeLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passLabel3 = new javax.swing.JLabel();
        jTextFieldPlaceholder1 = new com.mycompany.common.components.JTextFieldPlaceholder("Username");
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextFieldPlaceholder3 = new com.mycompany.common.components.JTextFieldPlaceholder("Name");
        jTextFieldPlaceholder4 = new com.mycompany.common.components.JTextFieldPlaceholder("Password");
        jTextFieldPlaceholder5 = new com.mycompany.common.components.JTextFieldPlaceholder("IBAN");
        jTextFieldPlaceholder6 = new com.mycompany.common.components.JTextFieldPlaceholder("Address");
        jTextFieldPlaceholder7 = new com.mycompany.common.components.JTextFieldPlaceholder("Surname");
        jTextFieldPlaceholder8 = new com.mycompany.common.components.JTextFieldPlaceholder("Telephone Number");
        providerView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            private static final long serialVersionUID = 1L;

            /*@Override
            public Class getColumnClass(int column) {
                return getValueAt(0, column).getClass();
            }*/
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    case 2:
                    return Boolean.class;
                    case 3:
                    return Boolean.class;
                    case 4:
                    return String.class;
                    case 5:
                    return String.class;
                    case 6:
                    return JButton.class;
                    default:
                    return String.class;
                }
            }
        };
        welcomeLabel2 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        OrderViewerCustomer = new javax.swing.JPanel();
        welcomeLabel4 = new javax.swing.JLabel();
        userLabel6 = new javax.swing.JLabel();
        userLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable(){

            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    default:
                    return String.class;
                }
            }
        };
        userLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        userLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        newSingup = new javax.swing.JPanel();
        passLabel4 = new javax.swing.JLabel();
        jTextFieldPlaceholder2 = new JTextFieldPlaceholder("Username");
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextFieldPlaceholder9 = new JTextFieldPlaceholder("Name");
        jTextFieldPlaceholder10 = new JTextFieldPlaceholder("Password");
        jTextFieldPlaceholder11 = new JTextFieldPlaceholder("IBAN");
        loginBtn2 = new javax.swing.JButton();
        jTextFieldPlaceholder12 = new JTextFieldPlaceholder("Address");
        signInBtn2 = new javax.swing.JButton();
        jTextFieldPlaceholder13 = new JTextFieldPlaceholder("Surname");
        welcomeLabel6 = new javax.swing.JLabel();
        jTextFieldPlaceholder14 = new JTextFieldPlaceholder("Telephone Number");
        jLabel3 = new javax.swing.JLabel();
        newLogin = new javax.swing.JPanel();
        signInBtn3 = new javax.swing.JButton();
        welcomeLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPlaceholder15 = new JTextFieldPlaceholder("Username");
        jTextFieldPlaceholder16 = new JTextFieldPlaceholder("Password");
        loginBtn4 = new javax.swing.JButton();
        newViewMenu = new javax.swing.JPanel();
        userLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable(){

            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    case 2:
                    return JButton.class;
                    default:
                    return String.class;
                }
            }
        };
        logoutBtn3 = new javax.swing.JButton();
        logoutBtn4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        userLabel3 = new javax.swing.JLabel();
        welcomeLabel7 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable(){

            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    case 2:
                    return JButton.class;
                    default:
                    return String.class;
                }
            }
        };
        userLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1747, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1747, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1747, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        userLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userLabel.setText("Username");

        passLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passLabel.setText("Password");

        userTextField.setBackground(new java.awt.Color(60, 63, 65));
        userTextField.setBorder(null);
        userTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTextFieldFocusGained(evt);
            }
        });
        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(44, 73, 129));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn.setText("Log In");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        signInBtn.setText("Sign Up");

        welcomeLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        welcomeLabel.setText("WELCOME");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setText("Don't have an account?");

        passTextField.setBackground(new java.awt.Color(60, 63, 65));
        passTextField.setBorder(null);
        passTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(signInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passTextField)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addComponent(jSeparator1))
                            .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addGap(102, 102, 102))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInBtn)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34))
        );

        loginBtn1.setBackground(new java.awt.Color(44, 73, 129));
        loginBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn1.setText("Sign Up");
        loginBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn1ActionPerformed(evt);
            }
        });

        signInBtn1.setText("Sign In");

        welcomeLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        welcomeLabel1.setText("SIGN UP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Already have an account?");

        passLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passLabel3.setText("Birthdate");

        jTextFieldPlaceholder1.setText("Username");
        jTextFieldPlaceholder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceholder1ActionPerformed(evt);
            }
        });

        jTextFieldPlaceholder3.setText("Name");
        jTextFieldPlaceholder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceholder3ActionPerformed(evt);
            }
        });

        jTextFieldPlaceholder4.setText("Password");
        jTextFieldPlaceholder4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceholder4ActionPerformed(evt);
            }
        });

        jTextFieldPlaceholder5.setText("IBAN");
        jTextFieldPlaceholder5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceholder5ActionPerformed(evt);
            }
        });

        jTextFieldPlaceholder6.setText("Address");
        jTextFieldPlaceholder6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceholder6ActionPerformed(evt);
            }
        });

        jTextFieldPlaceholder7.setText("Surname");
        jTextFieldPlaceholder7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceholder7ActionPerformed(evt);
            }
        });

        jTextFieldPlaceholder8.setText("Telephone Number");
        jTextFieldPlaceholder8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceholder8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPlaceholder6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(jTextFieldPlaceholder3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signUpPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPlaceholder4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(signUpPanelLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jTextFieldPlaceholder7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jTextFieldPlaceholder1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(loginBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signInBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldPlaceholder5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPlaceholder8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(2297, Short.MAX_VALUE))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(welcomeLabel1)
                .addGap(37, 37, 37)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jTextFieldPlaceholder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPlaceholder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPlaceholder4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPlaceholder7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPlaceholder5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPlaceholder6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPlaceholder8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signInBtn1)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47))
        );

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new NoEditableTableModel(
            new Object [][] {
                {null, null, true, false,null, null, new javax.swing.JButton()},
                {null, null, false, true, null, null, new javax.swing.JButton()},
                {null, null, true, true, null, null, new javax.swing.JButton()},
                {null, null, false, false, null, null, new javax.swing.JButton()}
            },
            new String [] {
                "<html><div style = 'text-align: center'>Provider Name</div></html>\"",
                "<html><div style = 'text-align: center'>Cuisine</div></html>\"",
                "<html><div style = 'text-align: center'>Do deliviring</div></html>\"",
                "<html><div style = 'text-align: center'>Do Take away</div></html>\"",
                "<html><div style = 'text-align: center'>Address</div></html>\"",
                "<html><div style = 'text-align: center'>Telephone</div></html>\"",
                ""
            },
            6
        ));
        jTable1.setDefaultRenderer(JButton.class,new JButtonRenderer(6, "Menù"));
        jTable1.setDefaultEditor(JButton.class,new JButtonEditor());
        jScrollPane1.setViewportView(jTable1);

        welcomeLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        welcomeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel2.setText("CHOOSE WHERE YOU WANNA EAT");

        logoutBtn.setBackground(new java.awt.Color(44, 73, 129));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutBtn.setText("Log out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout providerViewLayout = new javax.swing.GroupLayout(providerView);
        providerView.setLayout(providerViewLayout);
        providerViewLayout.setHorizontalGroup(
            providerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(providerViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(providerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(providerViewLayout.createSequentialGroup()
                        .addComponent(welcomeLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        providerViewLayout.setVerticalGroup(
            providerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, providerViewLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(providerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        welcomeLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        welcomeLabel4.setText("YOUR ORDER IN PROGRESS");

        userLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userLabel6.setText("Provider:  Nome provider");

        userLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userLabel7.setText("Order State:  Stato dell'ordine");

        jTable4.setModel(new NoEditableTableModel(
            new Object [][] {
                {null, null, },
                {null, null, },
                {null, null, },
                {null, null, }
            },
            new String [] {
                "<html><div style = 'text-align: center'>Dish Name</div></html>\"",
                "<html><div style = 'text-align: center'>Dish Price</div></html>\"",
                ""
            },
            10)
    );
    jScrollPane6.setViewportView(jTable4);

    userLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    userLabel8.setText("Your order");

    jTextArea3.setColumns(20);
    jTextArea3.setRows(5);
    jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dish Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    jScrollPane7.setViewportView(jTextArea3);

    jTextArea4.setColumns(20);
    jTextArea4.setRows(5);
    jTextArea4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dish Ingredient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    jScrollPane8.setViewportView(jTextArea4);

    userLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    userLabel9.setText("Total");

    jTextField2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout OrderViewerCustomerLayout = new javax.swing.GroupLayout(OrderViewerCustomer);
    OrderViewerCustomer.setLayout(OrderViewerCustomerLayout);
    OrderViewerCustomerLayout.setHorizontalGroup(
        OrderViewerCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(OrderViewerCustomerLayout.createSequentialGroup()
            .addGap(145, 145, 145)
            .addComponent(userLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(174, 174, 174))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderViewerCustomerLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane6)
            .addContainerGap())
        .addGroup(OrderViewerCustomerLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(OrderViewerCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(welcomeLabel4)
                .addComponent(userLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(OrderViewerCustomerLayout.createSequentialGroup()
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(userLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    OrderViewerCustomerLayout.setVerticalGroup(
        OrderViewerCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(OrderViewerCustomerLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(welcomeLabel4)
            .addGap(18, 18, 18)
            .addGroup(OrderViewerCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(userLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(userLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(OrderViewerCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(OrderViewerCustomerLayout.createSequentialGroup()
                    .addComponent(userLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(OrderViewerCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(OrderViewerCustomerLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(OrderViewerCustomerLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(OrderViewerCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userLabel9)))))
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(22, Short.MAX_VALUE))
    );

    passLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    passLabel4.setText("Birthdate");

    jTextFieldPlaceholder2.setText("Username");
    jTextFieldPlaceholder2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPlaceholder2ActionPerformed(evt);
        }
    });

    jTextFieldPlaceholder9.setText("Name");
    jTextFieldPlaceholder9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPlaceholder9ActionPerformed(evt);
        }
    });

    jTextFieldPlaceholder10.setText("Password");
    jTextFieldPlaceholder10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPlaceholder10ActionPerformed(evt);
        }
    });

    jTextFieldPlaceholder11.setText("IBAN");
    jTextFieldPlaceholder11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPlaceholder11ActionPerformed(evt);
        }
    });

    loginBtn2.setBackground(new java.awt.Color(44, 73, 129));
    loginBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    loginBtn2.setText("Sign Up");
    loginBtn2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            loginBtn2ActionPerformed(evt);
        }
    });

    jTextFieldPlaceholder12.setText("Address");
    jTextFieldPlaceholder12.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPlaceholder12ActionPerformed(evt);
        }
    });

    signInBtn2.setText("Sign In");

    jTextFieldPlaceholder13.setText("Surname");
    jTextFieldPlaceholder13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPlaceholder13ActionPerformed(evt);
        }
    });

    welcomeLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
    welcomeLabel6.setText("SIGN UP");

    jTextFieldPlaceholder14.setText("Telephone Number");
    jTextFieldPlaceholder14.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPlaceholder14ActionPerformed(evt);
        }
    });

    jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
    jLabel3.setText("Already have an account?");

    javax.swing.GroupLayout newSingupLayout = new javax.swing.GroupLayout(newSingup);
    newSingup.setLayout(newSingupLayout);
    newSingupLayout.setHorizontalGroup(
        newSingupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newSingupLayout.createSequentialGroup()
            .addGap(46, 46, 46)
            .addGroup(newSingupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jTextFieldPlaceholder12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(welcomeLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(newSingupLayout.createSequentialGroup()
                    .addComponent(jTextFieldPlaceholder9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newSingupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(newSingupLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPlaceholder10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(newSingupLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jTextFieldPlaceholder13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addComponent(jTextFieldPlaceholder2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(newSingupLayout.createSequentialGroup()
                    .addComponent(loginBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(signInBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jTextFieldPlaceholder11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldPlaceholder14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(45, Short.MAX_VALUE))
    );
    newSingupLayout.setVerticalGroup(
        newSingupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newSingupLayout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(welcomeLabel6)
            .addGap(38, 38, 38)
            .addGroup(newSingupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newSingupLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jTextFieldPlaceholder9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(passLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newSingupLayout.createSequentialGroup()
                    .addGroup(newSingupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldPlaceholder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPlaceholder10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jTextFieldPlaceholder13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addComponent(jTextFieldPlaceholder11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldPlaceholder12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldPlaceholder14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(newSingupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loginBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(signInBtn2)
                .addComponent(jLabel3))
            .addContainerGap(34, Short.MAX_VALUE))
    );

    signInBtn3.setText("Sign Up");

    welcomeLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
    welcomeLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    welcomeLabel5.setText("WELCOME");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
    jLabel4.setText("Don't have an account?");

    jTextFieldPlaceholder15.setText("Username");
    jTextFieldPlaceholder15.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPlaceholder15ActionPerformed(evt);
        }
    });

    jTextFieldPlaceholder16.setText("Password");
    jTextFieldPlaceholder16.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPlaceholder16ActionPerformed(evt);
        }
    });

    loginBtn4.setBackground(new java.awt.Color(44, 73, 129));
    loginBtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    loginBtn4.setText("Log In");
    loginBtn4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            loginBtn4ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout newLoginLayout = new javax.swing.GroupLayout(newLogin);
    newLogin.setLayout(newLoginLayout);
    newLoginLayout.setHorizontalGroup(
        newLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newLoginLayout.createSequentialGroup()
            .addGap(124, 124, 124)
            .addGroup(newLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTextFieldPlaceholder16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldPlaceholder15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newLoginLayout.createSequentialGroup()
            .addContainerGap(82, Short.MAX_VALUE)
            .addGroup(newLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newLoginLayout.createSequentialGroup()
                    .addGroup(newLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(loginBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(welcomeLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(102, 102, 102))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newLoginLayout.createSequentialGroup()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(signInBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(70, 70, 70))))
    );
    newLoginLayout.setVerticalGroup(
        newLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newLoginLayout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addComponent(welcomeLabel5)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldPlaceholder15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldPlaceholder16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(loginBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(newLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(signInBtn3)
                .addComponent(jLabel4))
            .addContainerGap(24, Short.MAX_VALUE))
    );

    userLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    userLabel10.setText("Your order");

    jTable5.setModel(new NoEditableTableModel(
        new Object [][] {
            {null, null, new javax.swing.JButton()},
            {null, null, new javax.swing.JButton()},
            {null, null, new javax.swing.JButton()},
            {null, null, new javax.swing.JButton()}
        },
        new String [] {
            "<html><div style = 'text-align: center'>Dish Name</div></html>\"",
            "<html><div style = 'text-align: center'>Dish Price</div></html>\"",
            ""
        },
        2
    ));
    jTable5.setDefaultRenderer(JButton.class,new JButtonRenderer(2,"Remove from your order"));
    jTable5.setDefaultEditor(JButton.class,new JButtonEditor());
    jScrollPane9.setViewportView(jTable5);

    logoutBtn3.setBackground(new java.awt.Color(44, 73, 129));
    logoutBtn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    logoutBtn3.setText("Return to provider choise");
    logoutBtn3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutBtn3ActionPerformed(evt);
        }
    });

    logoutBtn4.setBackground(new java.awt.Color(44, 73, 129));
    logoutBtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    logoutBtn4.setText("Confirm your order");
    logoutBtn4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutBtn4ActionPerformed(evt);
        }
    });

    jTextField3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField3ActionPerformed(evt);
        }
    });

    jTextArea5.setColumns(20);
    jTextArea5.setRows(5);
    jTextArea5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dish Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    jScrollPane10.setViewportView(jTextArea5);

    jTextArea6.setColumns(20);
    jTextArea6.setRows(5);
    jTextArea6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dish Ingredient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    jScrollPane11.setViewportView(jTextArea6);

    buttonGroup1.add(jRadioButton3);
    jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jRadioButton3.setText("Home delivery");
    jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButton3ActionPerformed(evt);
        }
    });

    buttonGroup1.add(jRadioButton4);
    jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jRadioButton4.setText("Take Away");

    userLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    userLabel3.setText("Total");

    welcomeLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
    welcomeLabel7.setText("CHOOSE YOUR DISHES");

    jTable6.setModel(new NoEditableTableModel(
        new Object [][] {
            {null, null, new javax.swing.JButton()},
            {null, null, new javax.swing.JButton()},
            {null, null, new javax.swing.JButton()},
            {null, null, new javax.swing.JButton()}
        },
        new String [] {
            "<html><div style = 'text-align: center'>Dish Name</div></html>\"",
            "<html><div style = 'text-align: center'>Dish Price</div></html>\"",
            ""
        },
        2
    ));
    jTable6.setDefaultRenderer(JButton.class,new JButtonRenderer(2,"Add to your order"));
    jTable6.setDefaultEditor(JButton.class,new JButtonEditor());
    jScrollPane12.setViewportView(jTable6);

    userLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    userLabel11.setText("Menù of  Nome Provider");

    javax.swing.GroupLayout newViewMenuLayout = new javax.swing.GroupLayout(newViewMenu);
    newViewMenu.setLayout(newViewMenuLayout);
    newViewMenuLayout.setHorizontalGroup(
        newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newViewMenuLayout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addGroup(newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newViewMenuLayout.createSequentialGroup()
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(newViewMenuLayout.createSequentialGroup()
                            .addComponent(jRadioButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(newViewMenuLayout.createSequentialGroup()
                            .addComponent(logoutBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(newViewMenuLayout.createSequentialGroup()
                            .addGroup(newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(logoutBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(newViewMenuLayout.createSequentialGroup()
                                    .addComponent(userLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 12, Short.MAX_VALUE))))
                .addGroup(newViewMenuLayout.createSequentialGroup()
                    .addGroup(newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(welcomeLabel7)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                            .addComponent(jScrollPane12)))
                    .addContainerGap())))
    );
    newViewMenuLayout.setVerticalGroup(
        newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newViewMenuLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(welcomeLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(userLabel11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(userLabel10)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newViewMenuLayout.createSequentialGroup()
                    .addGroup(newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userLabel3))
                    .addGap(18, 18, 18)
                    .addComponent(logoutBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(newViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton3))
                    .addGap(23, 23, 23)
                    .addComponent(logoutBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(38, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap(1005, Short.MAX_VALUE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(providerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1979, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(OrderViewerCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newSingup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap())
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(signUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(providerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(OrderViewerCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newSingup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldActionPerformed

    private void passTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    private void userTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldFocusGained

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextFieldPlaceholder7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder7ActionPerformed

    private void jTextFieldPlaceholder6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder6ActionPerformed

    private void jTextFieldPlaceholder5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder5ActionPerformed

    private void jTextFieldPlaceholder4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder4ActionPerformed

    private void jTextFieldPlaceholder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder3ActionPerformed

    private void jTextFieldPlaceholder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder1ActionPerformed

    private void loginBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1ActionPerformed

    private void jTextFieldPlaceholder8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder8ActionPerformed

    private void jTextFieldPlaceholder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder2ActionPerformed

    private void jTextFieldPlaceholder9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder9ActionPerformed

    private void jTextFieldPlaceholder10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder10ActionPerformed

    private void jTextFieldPlaceholder11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder11ActionPerformed

    private void loginBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2ActionPerformed

    private void jTextFieldPlaceholder12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder12ActionPerformed

    private void jTextFieldPlaceholder13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder13ActionPerformed

    private void jTextFieldPlaceholder14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder14ActionPerformed

    private void jTextFieldPlaceholder15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder15ActionPerformed

    private void jTextFieldPlaceholder16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceholder16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceholder16ActionPerformed

    private void loginBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn4ActionPerformed

    private void logoutBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtn3ActionPerformed

    private void logoutBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtn4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OrderViewerCustomer;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder1;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder10;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder11;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder12;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder13;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder14;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder15;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder16;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder2;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder3;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder4;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder5;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder6;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder7;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder8;
    private com.mycompany.common.components.JTextFieldPlaceholder jTextFieldPlaceholder9;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton loginBtn1;
    private javax.swing.JButton loginBtn2;
    private javax.swing.JButton loginBtn4;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton logoutBtn3;
    private javax.swing.JButton logoutBtn4;
    private javax.swing.JPanel newLogin;
    private javax.swing.JPanel newSingup;
    private javax.swing.JPanel newViewMenu;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passLabel3;
    private javax.swing.JLabel passLabel4;
    private javax.swing.JTextField passTextField;
    private javax.swing.JPanel providerView;
    private javax.swing.JButton signInBtn;
    private javax.swing.JButton signInBtn1;
    private javax.swing.JButton signInBtn2;
    private javax.swing.JButton signInBtn3;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userLabel10;
    private javax.swing.JLabel userLabel11;
    private javax.swing.JLabel userLabel3;
    private javax.swing.JLabel userLabel6;
    private javax.swing.JLabel userLabel7;
    private javax.swing.JLabel userLabel8;
    private javax.swing.JLabel userLabel9;
    private javax.swing.JTextField userTextField;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeLabel1;
    private javax.swing.JLabel welcomeLabel2;
    private javax.swing.JLabel welcomeLabel4;
    private javax.swing.JLabel welcomeLabel5;
    private javax.swing.JLabel welcomeLabel6;
    private javax.swing.JLabel welcomeLabel7;
    // End of variables declaration//GEN-END:variables
}
